name: Create Release

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MOTOIL_APP_ID }}
          private-key: ${{ secrets.MOTOIL_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Download Libs from GitHub Release
        run: |
          mkdir -p libs-bin
          gh release download --repo motoil-nn-ru/libs --pattern "*.jar" --dir libs-bin
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bootJar \
            -PmotulNexusUrl="https://repo.maven.apache.org/maven2" \
            -PmotulNexusUser="none" \
            -PmotulNexusPassword="none" \
            -x test

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep 'version=' version.properties | cut -d'=' -f2 | xargs)
          echo "project_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.project_version }}
          name: Release ${{ steps.get_version.outputs.project_version }}
          files: |
            **/build/libs/*[!plain].jar
          body: |
            Автоматический релиз сервиса ${{ github.event.repository.name }}.
          generate_release_notes: true